# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# KSP Optimizations
ksp.incremental=true

# Desactivar motor KSP2 para evitar errores de firma JVM en versiones actuales
ksp.useKsp2=false

# Soporte esencial para librerías AndroidX
android.useAndroidX=true
android.enableJetifier=true
